CREATE DATABASE IF NOT EXISTS parking_db;
USE parking_db;

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  rol ENUM('ADMINISTRADOR', 'OPERADOR') DEFAULT 'OPERADOR',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE espacios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  numero VARCHAR(10) NOT NULL,
  zona VARCHAR(5) NOT NULL,
  tipo ENUM('CARRO', 'MOTO', 'DISCAPACITADO') DEFAULT 'CARRO',
  estado ENUM('DISPONIBLE', 'OCUPADO', 'RESERVADO') DEFAULT 'DISPONIBLE',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE registros (
  id INT AUTO_INCREMENT PRIMARY KEY,
  placa VARCHAR(10) NOT NULL,
  espacioId INT NOT NULL,
  tipoVehiculo ENUM('CARRO', 'MOTO') DEFAULT 'CARRO',
  horaIngreso DATETIME NOT NULL,
  horaSalida DATETIME NULL,
  minutosTotal INT NULL,
  totalPagar DECIMAL(10,2) NULL,
  operadorId INT NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (espacioId) REFERENCES espacios(id),
  FOREIGN KEY (operadorId) REFERENCES usuarios(id)
);

CREATE TABLE tarifas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tipoVehiculo ENUM('CARRO', 'MOTO') NOT NULL,
  valorHora DECIMAL(10,2) NOT NULL,
  activa BOOLEAN DEFAULT TRUE,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Datos iniciales
INSERT INTO usuarios (nombre, email, password, rol) VALUES
('Admin ParkingControl', 'admin@parking.com', '$2a$12$x.RV2O1Ze6xwCwqwaduQWeomhvTl4eB6Xy3l3W2DcFTL2FwVv/oea', 'ADMINISTRADOR'),
('Operador 1', 'operador@parking.com', '$2a$12$x.RV2O1Ze6xwCwqwaduQWeomhvTl4eB6Xy3l3W2DcFTL2FwVv/oea', 'OPERADOR');
-- Contrasena para ambos: parking123

INSERT INTO espacios (numero, zona, tipo, estado) VALUES
('A01', 'A', 'CARRO', 'DISPONIBLE'),
('A02', 'A', 'CARRO', 'DISPONIBLE'),
('A03', 'A', 'CARRO', 'DISPONIBLE'),
('A04', 'A', 'MOTO', 'DISPONIBLE'),
('B01', 'B', 'CARRO', 'DISPONIBLE'),
('B02', 'B', 'CARRO', 'DISPONIBLE'),
('B03', 'B', 'DISCAPACITADO', 'DISPONIBLE');

INSERT INTO tarifas (tipoVehiculo, valorHora, activa) VALUES
('CARRO', 3000, TRUE),
('MOTO', 1500, TRUE);
